openapi: 3.0.0
info:
  title: Test d'orientation du Covid-19
  version: '2020-03-30 20:01:39.836837Z'
servers:
  - url: 'http://localhost:4000'
    variables: {}
paths:
  /questionnaire:
    post:
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionnaireResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Évaluer le test d'orientation du Covid-19
      operationId: QuestionnaireController.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireRequest'
        description: Paramètres du test d'orientation
        required: true
      summary: Évaluer le test d'orientation du Covid-19
components:
  responses: {}
  schemas:
    Conclusion:
      description: >-
        [Conclusion de l'questionnaire du
        Covid-19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
      example:
        code: orientation_SAMU
      properties:
        code:
          description: >-
            [Conclusions
            possibles](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
          enum:
            - orientation_SAMU
            - FIN2
            - FIN3
            - FIN4
            - FIN5
            - FIN6
            - FIN7
            - FIN8
            - FIN9
          type: string
      required:
        - code
      title: Conclusion
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Conclusion
    Metadata:
      description: >-
        [Caractéristiques du
        questionnaire](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        algo_version: '2020-03-29 15:20:11.875767Z'
        date: '2020-03-29 15:20:11.875767Z'
        duration: 3600
        form_version: '2020-03-29 15:20:11.875767Z'
      properties:
        algo_version:
          description: Version de l'algorithme médical
          format: date-time
          type: string
        date:
          description: Date de fin de remplissage du questionnaire
          format: date-time
          type: string
        duration:
          description: Durée de remplissage du questionnaire (seconds)
          type: integer
        form_version:
          description: Version du questionnaire
          format: date-time
          type: string
      required:
        - duration
      title: Metadata
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Metadata
    Patient:
      description: >-
        [Caractéristiques du
        patient](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        age_less_15: false
        age_less_50: false
        age_less_70: false
        age_more_70: true
        height: 173
        postal_code: '75000'
        weight: 65.5
      properties:
        age_less_15:
          description: Si la personne a moins de 15 ans
          type: boolean
        age_less_50:
          description: Si la personne a moins de 50 ans
          type: boolean
        age_less_70:
          description: Si la personne a moins de 70 ans
          type: boolean
        age_more_70:
          description: Si la personne a au moins 70 ans
          type: boolean
        height:
          description: Quelle est votre taille en centimètres ?
          type: integer
        postal_code:
          description: Code postal
          type: string
        weight:
          description: Quel est votre poids en kilogrammes ?
          type: number
      title: Patient
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Patient
    Pronostiques:
      description: >-
        [Questions sur les facteurs pronostiques défavorables au
        terrain](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-facteurs-pronostiques-d%C3%A9favorables-au-terrain)
      example:
        breathing_disease: true
        cancer: true
        diabetes: true
        heart_disease: true
        immunodeprime: true
        immunosuppressant_drug: true
        kidney_disease: true
        liver_disease: true
        pregnant: true
      properties:
        breathing_disease:
          description: >-
            Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un
            pneumologue ?
          type: boolean
        cancer:
          description: Avez-vous ou avez-vous eu un cancer ?
          type: boolean
        diabetes:
          description: Êtes-vous diabétique ?
          type: boolean
        heart_disease:
          description: >-
            Avez-vous une tension artérielle mal équilibrée ? Ou une maladie
            cardiaque ou vasculaire ? Ou prenez-vous un traitement à visée
            cardiologique ?
          type: boolean
        immunodeprime:
          description: >-
            Avez-vous une maladie connue pour diminuer vos défenses immunitaires
            ?
          type: boolean
        immunosuppressant_drug:
          description: Prenez-vous un traitement immunosuppresseur ?
          type: boolean
        kidney_disease:
          description: Avez-vous une insuffisance rénale chronique dialysée ?
          type: boolean
        liver_disease:
          description: Avez-vous une maladie chronique du foie ?
          type: boolean
        pregnant:
          description: Êtes-vous enceinte ?
          type: boolean
      title: Pronostiques
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Pronostiques
    Questionnaire:
      description: >-
        [Algorithme d'orientation du
        Covid-19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#pr%C3%A9sentation-de-lalgorithme-dquestionnaire-covid19)
      example:
        conclusion:
          code: orientation_SAMU
        metadata:
          algo_version: '2020-03-29 15:20:11.875767Z'
          date: '2020-03-29 15:20:11.875767Z'
          duration: 3600
          form_version: '2020-03-29 15:20:11.875767Z'
        patient:
          age_less_15: false
          age_less_50: false
          age_less_70: false
          age_more_70: true
          height: 173
          postal_code: '75000'
          weight: 65.5
        pronostiques:
          breathing_disease: true
          cancer: true
          diabetes: true
          heart_disease: true
          immunodeprime: true
          immunosuppressant_drug: true
          kidney_disease: true
          liver_disease: true
          pregnant: true
        statistiques:
          au_moins_30_imc: true
          au_moins_39_de_temperature: true
          facteurs_gravite: 3
          facteurs_gravite_majeurs: 1
          facteurs_gravite_mineurs: 2
          facteurs_pronostique: 1
          fever: true
          heart_disease: true
        symptomes:
          agueusia_anosmia: true
          breathlessness: true
          cough: true
          diarrhea: true
          feeding: true
          sore_throat_aches: true
          temperature: 37.5
          tiredness: true
      properties:
        conclusion:
          $ref: '#/components/schemas/Conclusion'
        metadata:
          $ref: '#/components/schemas/Metadata'
        patient:
          $ref: '#/components/schemas/Patient'
        pronostiques:
          $ref: '#/components/schemas/Pronostiques'
        statistiques:
          $ref: '#/components/schemas/Statistiques'
        symptomes:
          $ref: '#/components/schemas/Symptomes'
      required:
        - metadata
        - patient
        - symptomes
        - pronostiques
      title: Questionnaire
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Questionnaire
    QuestionnaireRequest:
      description: Corps de la requête POST pour lancer l'algorithme d'orientation
      example:
        questionnaire:
          metadata:
            duration: 3600
          patient:
            age_less_15: false
            age_less_50: false
            age_less_70: false
            age_more_70: true
            height: 173
            postal_code: '75000'
            weight: 65.5
          pronostiques:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: true
            immunodeprime: true
            immunosuppressant_drug: true
            kidney_disease: true
            liver_disease: true
            pregnant: true
          symptomes:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding: true
            sore_throat_aches: true
            temperature: 37.5
            tiredness: true
      properties:
        questionnaire:
          anyOf:
            - $ref: '#/components/schemas/Questionnaire'
      required:
        - questionnaire
      title: QuestionnaireRequest
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireRequest
    QuestionnaireResponse:
      description: Réponse de l'algorithme d'orientation
      example:
        data:
          conclusion:
            code: FIN5
          metadata:
            algo_version: '2020-03-30 20:01:39.836837Z'
            date: '2020-03-29 15:20:11.875767Z'
            duration: 3600
            form_version: '2020-03-30 20:01:39.836837Z'
          patient:
            age_less_15: false
            age_less_50: false
            age_less_70: false
            age_more_70: true
            height: 173
            postal_code: '75000'
            weight: 65.5
          pronostiques:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: true
            immunodeprime: true
            immunosuppressant_drug: true
            kidney_disease: true
            liver_disease: true
            pregnant: true
          statistiques:
            au_moins_30_imc: false
            au_moins_39_de_temperature: false
            facteurs_gravite: 3
            facteurs_gravite_majeurs: 2
            facteurs_gravite_mineurs: 1
            facteurs_pronostique: 10
            fever: false
            heart_disease: true
          symptomes:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding: true
            sore_throat_aches: true
            temperature: 37.5
            tiredness: true
      properties:
        data:
          $ref: '#/components/schemas/Questionnaire'
      title: QuestionnaireResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireResponse
    Statistiques:
      description: >-
        [Statistiques](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/implementation.org#conseils-pour-limpl%C3%A9mentation-de-lalgorithme)
      example:
        au_moins_39_de_temperature: true
        facteurs_gravite: 3
        facteurs_gravite_majeurs: 1
        facteurs_gravite_mineurs: 2
        facteurs_pronostique: 1
        fever: true
        heart_disease: true
      properties:
        au_moins_30_imc:
          description: Si la personne a au moins 30 d'IMC en kg/m2
          type: boolean
        au_moins_39_de_temperature:
          description: Si la personne a au moins 39°C de température
          type: boolean
        facteurs_gravite:
          description: Facteurs de gravité mineurs + majeurs
          type: integer
        facteurs_gravite_majeurs:
          description: Facteurs de gravité majeurs
          type: integer
        facteurs_gravite_mineurs:
          description: Facteurs de gravité mineurs
          type: integer
        facteurs_pronostique:
          description: Facteurs pronostique défavorables liés au terrain
          type: integer
        fever:
          description: Indicateur de fièvre
          type: boolean
        heart_disease:
          description: Si la personne a des problèmes d'hypertension / cardiaques
          type: boolean
      required:
        - fever
        - au_moins_39_de_temperature
        - heart_disease
        - facteurs_gravite
        - facteurs_gravite_mineurs
        - facteurs_gravite_majeurs
        - facteurs_pronostique
      title: Statistiques
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Statistiques
    Symptomes:
      description: >-
        [Questions sur les
        symptômes](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-sympt%C3%B4mes)
      example:
        agueusia_anosmia: true
        breathlessness: true
        cough: true
        diarrhea: true
        feeding: true
        sore_throat_aches: true
        temperature: 37.5
        tiredness: true
      properties:
        agueusia_anosmia:
          description: >-
            Avez-vous noté une forte diminution de votre goût ou de l’odorat ces
            derniers jours ?
          type: boolean
        breathlessness:
          description: >-
            Dans les dernières 24 heures, avez-vous noté un manque de souffle
            INHABITUEL lorsque vous parlez ou faites un petit effort ?
          type: boolean
        cough:
          description: >-
            Avez-vous une toux ou une augmentation de votre toux habituelle ces
            derniers jours ?
          type: boolean
        diarrhea:
          description: >-
            Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles
            molles) ?
          type: boolean
        feeding:
          description: >-
            Êtes-vous dans l’impossibilité de vous alimenter ou boire DEPUIS 24
            HEURES OU PLUS ?
          type: boolean
        sore_throat_aches:
          description: Avez-vous un mal de gorge apparu ces derniers jours ?
          type: boolean
        temperature:
          description: >-
            Pensez-vous avoir eu de la fièvre ces derniers jours (frissons,
            sueurs) ? Quelle est votre température ?
          type: number
        tiredness:
          description: >-
            Avez-vous une fatigue inhabituelle ces derniers jours ? Cette
            fatigue vous oblige-t-elle à vous reposer plus de la moitié de la
            journée ?
          type: boolean
      title: Symptomes
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Symptomes
security: []
tags: []

